### ISSUE TITLE
Clarify that used Repositories should use / extend the SpecificationRepository

### ISSUE THREAD

**Issue by holtkamp** [rikbruil/Doctrine-Specification#11]
Nice package! Took me some searching to understand that my Repositories need to either:
- be configured to "be" the SpecificationRepository
- extend the SpecificationRepository

Maybe a small section about this in the README?

**Comment by rikbruil** [comment]
I have just merged some changes that add a note to the top of the README.

The requirement to extend SpecificationRepository is gone, you can use a combination of the SpecificationRepositoryTrait and SpecificationAwareInterface in your own custom repository classes now. 

The old SpecificationRepository class is still provided for backwards compatibility though (or if you don't mind extending).

**Comment by holtkamp** [comment]
Great! Closing issue 😉
