### ISSUE TITLE
isMemberOf Condition missing

### ISSUE THREAD

**Issue by holtkamp** [rikbruil/Doctrine-Specification#25]
Just encountered a case requiring the `isMemberOf` Condition. This seems currently not supported. 

I guess it would be quite similar to https://github.com/rikbruil/Doctrine-Specification/blob/e61fb801c46107b0a9ce22086448557def7fa532/src/Condition/IsInstanceOf.php

**Comment by rikbruil** [comment]
Yes it appears so, feel free to create a PR, otherwise I will take a look at this myself later.

**Comment by holtkamp** [comment]
Realized by https://github.com/rikbruil/Doctrine-Specification/pull/27, closing issue
